### PR TITLE
small fixes

### PR DESCRIPTION
**Pull request by Govorunb**

### CODE REVIEW

**Comment by Alexejhero** [comment]
Should this be merged into upstream?

**Comment by Govorunb** [comment]
Maybe if the PR was a bit meatier - it's way too small imo
I only opened it because you have main protected here xdx

**Comment by Alexejhero** [comment]
I think you should PR this into main instead

**Comment by Alexejhero** [comment]
I have main protected because I want to diverge from upstream as little as possible

**Comment by Alexejhero** [comment]
Pull request created in upstream: https://github.com/codewriter-packages/Tri-Inspector/pull/144

**Pull request closed without merging**
